FORMAT: 1A
HOST: http://newsr.me/

# Newsr

Newsr has a simple API allowing users to view news articles related to 
specific countries or from certain news organizations.

## News Articles Collection [/api/articles/]

### List News Articles [GET]

+ Response 200 (application/json)

        [
            {
                "id": "cjlka4x-4w4xw",
                "source": {
                    "id": "sx4498f-32"
                },
                "countries": [
                    {
                        "id": "x38c-2d"
                    }
                ],
                "author": "Pamela Brown, Evan Perez and Shimon Prokupecz, CNN",
                "title": "US Officials: Info suggests Trump associates may have coordinated with Russians",
                "description": "The FBI has information that indicates associates of President Donald Trump communicated with suspected Russian operatives to possibly coordinate the release of information damaging to Hillary Clinton's campaign, US officials told CNN.",
                "url": "http://us.cnn.com/2017/03/22/politics/us-officials-info-suggests-trump-associates-may-have-coordinated-with-russians/index.html",
                "imageUrl": "http://i2.cdn.cnn.com/cnnnext/dam/assets/170320125707-05-comey-hearing-0320-super-tease.jpg",
                "publishDate": "2017-03-23T00:40:04Z"
            }
        ]
        
## News Article Information Collection [/api/articles/{article_id}]

### Get information for a news article [GET] 

+ Parameters
    + article_id (number) - ID of the article

+ Response 200 (application/json)

        {
            "id": "cjlka4x-4w4xw",
            "source": {
                "id": "sx4498f-32"
            },
            "countries": [
                {
                    "id": "x38c-2d"
                }
            ],
            "author": "Pamela Brown, Evan Perez and Shimon Prokupecz, CNN",
            "title": "US Officials: Info suggests Trump associates may have coordinated with Russians",
            "description": "The FBI has information that indicates associates of President Donald Trump communicated with suspected Russian operatives to possibly coordinate the release of information damaging to Hillary Clinton's campaign, US officials told CNN.",
            "url": "http://us.cnn.com/2017/03/22/politics/us-officials-info-suggests-trump-associates-may-have-coordinated-with-russians/index.html",
            "imageUrl": "http://i2.cdn.cnn.com/cnnnext/dam/assets/170320125707-05-comey-hearing-0320-super-tease.jpg",
            "publishDate": "2017-03-23T00:40:04Z"
        }


## Organizations Collection [/api/organizations/]

### List News Organizations [GET]
    
+ Response 200 (application/json)

        [
            
            {
                "id": "cnn",
                "country": {
                    "id": "sldk83"
                },
                "articles": [
                    {
                        "id": "49s9xk3"
                    }
                ],
                "name": "CNN",
                "description": "View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN",
                "url": "http://us.cnn.com",
                "logoUrl": "http://i.newsapi.org/cnn-l.png"
            }
        ]
        
## Organization Information Collection [/api/organizations/{org_id}]

### Get information for an organization [GET] 

+ Parameters
    + org_id (number) - ID of the organization 

+ Response 200 (application/json)

        {
            
            "id": "cnn",
            "country": {
                "id": "sldk83"
            },
            "articles": [
                {
                    "id": "49s9xk3"
                }
            ],
            "name": "CNN",
            "description": "View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN",
            "url": "http://us.cnn.com",
            "logoUrl": "http://i.newsapi.org/cnn-l.png"
            
        }

## Countries Collection [/api/countries/]

### List Countries [GET]

+ Response 200 (application/json)

        [
           
            {
                "id": "an",
                "sources": [
                    {
                        "id": "4sx49"
                    }
                ],
                "articles": [],
                "name":"Andorra",
                "capital":"Andorra la Vella",
                "region":"Europe",
                "population": 78014,
                "flagUrl": "https://restcountries.eu/data/and.svg"
            }
        ]
        
## Countries Information Collection [/api/countries/{country_id}]

### Get information for a country [GET] 

+ Parameters
    + country_id (number) - ID of the country

+ Response 200 (application/json)

        {
            "id": "an",
            "sources": [
                {
                    "id": "4sx49"
                }
            ],
            "articles": [],
            "name":"Andorra",
            "capital":"Andorra la Vella",
            "region":"Europe",
            "population": 78014,
            "flagUrl": "https://restcountries.eu/data/and.svg"
        }
        
## Tests Results Collection [/tests/]

### Get results of running unit tests [GET]

+ Response 200 (application/json)

        {
            "test_results": "............... ---------------------------------------------------------------------- Ran 15 tests in 0.082s OK"
        }
